### ISSUE TITLE
The document/paper 

### ISSUE THREAD

**Issue by Aysticky** [akashavverma/Routing-Algorithms-For-Enenrgy-Efficiency-In-UWSNs#3]
Please can you upload or give the paper link of this wonderful implemented UWSN? Thank you.

**Comment by akashavverma** [comment]
Sorry but this algorithm still require development and we have not published any papers for it. If in future we do so, I would be very happy to provide you the same.

**Comment by Aysticky** [comment]
Dear Dr. Akash,

Thank you for your reply. However, please note that I am not asking for
published paper, it can be any form of text material that shows the
mathematical equations of this implemented algorithm. Just to theoretically
know where the blueprint of this algorithm came from.

If your answer is still same, I would understand that too.


Yours sincerely,

Ayobami Meadows, MSc.
Department of Computer and Control Engineering.
Ahmadu Bello University, Zaria.
***@***.***
***@***.***
+234-7030727885
https://www.linkedin.com/in/ayobami-meadows-38016568

**Comment by akashavverma** [comment]
Dear Ayobami,
I am pursuing Masters as of now. Please use 'Akash' only as I am not yet eligible for "Dr.". It's great to know you have interest in this project. Here you can find more details about the project. 
https://routingprotocolforuswn.blogspot.com/2020/06/routing-algorithms-for-energy.html
If you need any more information, please drop a mail to me.

Thanks & Regards,
Akash Verma
MTech CSE AI
(+91) 9993781846, akashverma.av98@gmail.com
IIIT Delhi

**Comment by Aysticky** [comment]
Thank you Mr. Akash for the provided link. Although it still does not show
the mathematical equations leading to the algorithm development. But it's
all good and okay.

Thank you for your time.


Yours sincerely,

Ayobami Meadows, MSc.
Department of Computer and Control Engineering.
Ahmadu Bello University, Zaria.
***@***.***
***@***.***
+234-7030727885
https://www.linkedin.com/in/ayobami-meadows-38016568
